title: Moulmein-Cairnhill
url: https://moulmeincairnhill.pa.gov.sg
favicon: /images/60ef2b999757da7b73ab4e6a_Favicon.png
colors:
  primary-color: "#da1f34"
  secondary-color: "#316b99"
  media-colors:
    - title: media-color-one
      color: "#2a2d42"
    - title: media-color-two
      color: "#1d4575"
    - title: media-color-three
      color: "#1d4575"
    - title: media-color-four
      color: "#d0021b"
    - title: media-color-five
      color: "#d0021b"
description: Moulmein-Cairnhill (affectionately known as "MoCa") is a division
  under the Tanjong Pagar GRC, helmed by our Grassroots Advisor, Mr Alvin Tan.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2ykz61gaxoc4q.amplifyapp.com
prod: https://master.d2ykz61gaxoc4q.amplifyapp.com
facebook-pixel: ""
shareicon: /images/og.jpg
is_government: false
google_analytics_ga4: G-S6P2KD4BVD
linkedin-insights: ""
resources_name: moulmein-cairnhill
